/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cardealer;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author semih
 */
public class frm_Buying extends javax.swing.JInternalFrame {

    /**
     * Creates new form buying
     */
    public frm_Buying() {
        initComponents();
        refresh();
    }

    cl_Cars car = new cl_Cars();
    sl_Brands sBrand = new sl_Brands();
    sl_Models sModel = new sl_Models();
    sl_CarList sCar = new sl_CarList();
    sl_Users sUser = new sl_Users();
    sl_Process sProc = new sl_Process();
    mail sendMail = new mail();
    
    private void refresh(){
        addItemCmbBrands();
        addItemCmbModels();
    }
    
    private void addItemCmbBrands(){
        cmbCarBrands.removeAllItems();
        
        ArrayList<cl_Brands> brands = sBrand.get_Brands();
        
        for(cl_Brands brand : brands){
            cmbCarBrands.addItem(brand);
        }
    }
    
    private void addItemCmbModels(){
        cmbCarModels.removeAllItems();
        
        cl_Brands brand = (cl_Brands) cmbCarBrands.getSelectedItem();
        ArrayList<cl_Models> models = sModel.get_Models(brand.getBrandID());
        
        for(cl_Models model : models){
            cmbCarModels.addItem(model);
        }
    }
    
    private void addCarItem(){
        cl_Brands brand = (cl_Brands) cmbCarBrands.getSelectedItem();
        cl_Models model = (cl_Models) cmbCarModels.getSelectedItem();
            
        car.setCarBrands(brand.getBrandID());
        car.setCarModels(model.getModelID());
        car.setCarPacket(txtCarPacket.getText().toUpperCase());
        car.setCarVIN(txtCarVIN.getText());
        car.setCarKm(txtCarKm.getText());
        car.setCarYear(txtCarYear.getText());
        car.setCarPlate(txtCarPlate.getText().toUpperCase());
        car.setCarPrice(txtCarPrice.getText());
        car.setCarComment(txtCarComment.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCarVIN = new javax.swing.JTextField();
        txtCarPacket = new javax.swing.JTextField();
        txtCarYear = new javax.swing.JTextField();
        txtCarKm = new javax.swing.JTextField();
        cmbCarBrands = new javax.swing.JComboBox<>();
        cmbCarModels = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCarComment = new javax.swing.JTextArea();
        cmbCarReport = new javax.swing.JComboBox<>();
        txtCarPrice = new javax.swing.JTextField();
        txtCarPlate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtUserID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBuying = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alım");

        jPanel1.setBackground(new java.awt.Color(225, 240, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Şase Numarası :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Marka :");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Model :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Km Bilgisi :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Yıl :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Paket :");

        txtCarVIN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtCarPacket.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtCarYear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtCarKm.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        cmbCarBrands.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbCarBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbCarBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarBrandsActionPerformed(evt);
            }
        });

        cmbCarModels.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbCarModels.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbCarModels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarModelsActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Alım Fiyatı :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Plaka :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Ekspertiz Raporu :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Açıklama :");

        txtCarComment.setColumns(20);
        txtCarComment.setRows(5);
        jScrollPane2.setViewportView(txtCarComment);

        cmbCarReport.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbCarReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yok", "Var" }));
        cmbCarReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtCarPrice.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtCarPlate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCarVIN, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(cmbCarBrands, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCarModels, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCarYear)
                    .addComponent(txtCarPacket))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(cmbCarReport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCarPrice)
                    .addComponent(txtCarPlate)
                    .addComponent(txtCarKm))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCarVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCarBrands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCarModels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCarPacket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCarReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtUserID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Kullanıcı ID :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addGap(372, 372, 372))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnBuying.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuying.setText("Alım Yap");
        btnBuying.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnBuying, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuying, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCarBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarBrandsActionPerformed
        // TODO add your handling code here:
        addItemCmbModels();
    }//GEN-LAST:event_cmbCarBrandsActionPerformed

    private void cmbCarModelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarModelsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbCarModelsActionPerformed

    private void btnBuyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyingActionPerformed
        // TODO add your handling code here:
        try{
            float chk = Float.valueOf(txtCarKm.getText());
            chk = Float.valueOf(txtCarYear.getText());
            chk = Float.valueOf(txtCarPrice.getText());
            chk = Float.valueOf(txtUserID.getText());
            
            cl_Brands brand = (cl_Brands) cmbCarBrands.getSelectedItem();
            cl_Models model = (cl_Models) cmbCarModels.getSelectedItem();
        
            if(sUser.isThereUser(txtUserID.getText())){
                if(txtCarVIN.getText().length() > 0){
                    if(!sCar.isThereStockCar(txtCarVIN.getText())){
                        if(sCar.isThereVIN(txtCarVIN.getText())){
                            if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(null, "Araba daha önceden alınmış bulunmakta.\nTekrardan almak istediğinize emin misiniz?", "Tekrarlanan Alım", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
                                if(sCar.isThereCar(txtCarVIN.getText(), brand.getBrandID(), model.getModelID(), txtCarYear.getText())){
                                    addCarItem();
                        
                                    if(cmbCarReport.getSelectedIndex() == 0){
                                        car.setCarReport(false);
                                    }else{
                                        car.setCarReport(true);
                                    }
                                
                                    boolean isAddCar = sCar.setBuy(car);
                                    boolean isAddProc = sProc.process(car, txtUserID.getText(), txtCarPrice.getText(),"ALIŞ");
                                
                                    if(isAddCar && isAddProc){
                                        String carBrandModelPlate = sCar.getCarBrandModel(txtCarVIN.getText());
                                        sendMail.sendMail(txtUserID.getText(), sProc.getID(), "ALIŞ", txtCarVIN.getText(), carBrandModelPlate);
                                        JOptionPane.showMessageDialog(null, "Araba alımı başarıyla gerçekleşti", "Başarılı Alım", JOptionPane.INFORMATION_MESSAGE);
                                    }else{
                                        if(isAddCar){
                                            sCar.cancelSetBuy(car);
                                        }
                                        if(isAddProc){
                                            sProc.cancelProcess(sProc.getID());
                                        }
                                        JOptionPane.showMessageDialog(null, "Araba alımı yapılamadı", "Başarısız Alım", JOptionPane.ERROR_MESSAGE);
                                    }
                                }else{
                                    JOptionPane.showMessageDialog(null, "Araba alımı yapılamadı,\nMarka/Model/Yıl bilgileri kayıtlı arabadan farklı!\nPolise haber verin", "Başarısız Alım", JOptionPane.ERROR_MESSAGE);
                                }
                            }   
                        }else{
                            addCarItem();
                        
                            if(cmbCarReport.getSelectedIndex() == 0){
                            car.setCarReport(false);
                            }else{
                                car.setCarReport(true);
                            }
                        
                            boolean isAddCar = sCar.buy(car);
                            boolean isAddProc = sProc.process(car, txtUserID.getText(), txtCarPrice.getText(), "ALIŞ");
                        
                            if(isAddCar && isAddProc){
                                String carBrandModelPlate = sCar.getCarBrandModel(txtCarVIN.getText());
                                sendMail.sendMail(txtUserID.getText(), sProc.getID(), "ALIŞ", txtCarVIN.getText(), carBrandModelPlate);
                                JOptionPane.showMessageDialog(null, "Araba alımı başarıyla gerçekleşti", "Başarılı Alım", JOptionPane.INFORMATION_MESSAGE);
                            }else{
                                if(isAddCar){
                                    sCar.cancelBuy(car);
                                }
                                if(isAddProc){
                                    sProc.cancelProcess(sProc.getID());
                                }
                                JOptionPane.showMessageDialog(null, "Araba alımı yapılamadı", "Başarısız Alım", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Araba alımı yapılamadı, araba stoklarınızda bulunmaktadır", "Başarısız Alım", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Araba alımı yapılamadı, Şase numarası boş geçilemez", "Başarısız Alım", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Kullanıcı kayıtlı değil, kullanıcıyı ekleyin", "Başarısız Alım", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hatalı değer girişi yapıldı!\nKullanıcı ID, Yıl, Km, Fiyat bilgilrti boş geçilemez ve sadece sayı girilebilir!", "Hatalı Giriş", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBuyingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuying;
    private javax.swing.JComboBox<cl_Brands> cmbCarBrands;
    private javax.swing.JComboBox<cl_Models> cmbCarModels;
    private javax.swing.JComboBox<String> cmbCarReport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCarComment;
    private javax.swing.JTextField txtCarKm;
    private javax.swing.JTextField txtCarPacket;
    private javax.swing.JTextField txtCarPlate;
    private javax.swing.JTextField txtCarPrice;
    private javax.swing.JTextField txtCarVIN;
    private javax.swing.JTextField txtCarYear;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
